#!/bin/bash
# ============================================================
# GUION 03 — Guía de grabación para el tutorial
# No ejecuta nada, es una guía de features para grabar
# ============================================================

echo "============================================"
echo " GUION 03 — Guía de grabación"
echo "============================================"
echo ""

echo "🎬 ORDEN PARA GRABAR (15-20 min total):"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 1 — Icono y Sidebar"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • Mostrá la activity bar con el icono AI a la izquierda"
echo " • Clickealo → se abre la sidebar con 5 secciones:"
echo "   📂 Evaluate"
echo "   🔧 Custom Evaluators"
echo "   🔑 Settings"
echo "   📖 Docs"
echo "   📋 Recent (vacío al principio)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 2 — Init project"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • Click en 📁 Init eval project"
echo " • Mostrar que se crearon los archivos:"
echo "   evals/smoke-test.json (5 queries)"
echo "   evals/smoke-test.jsonl (mismas queries en JSONL)"
echo "   evals/smoke-test-rag.json (3 queries con context)"
echo "   results/ (carpeta vacía para outputs)"
echo "   aievaluator.config.json"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 3 — Quick eval (selection)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • Abrí cualquier archivo, seleccioná un texto"
echo " • Click en ▶ Quick eval (selection) en la sidebar"
echo " • Elegí agente: 🧪 Internal agent (free)"
echo " • Seleccioná métricas (g_eval, faithfulness)"
echo " • Opcional: escribí expected output"
echo " • Click ▶ Run Evaluation"
echo " • Mostrar resultado en notificación"
echo " • Mostrar que aparece en 📋 Recent → click para expandir:"
echo "   🤖 Agent Response + 🎯 Expected + scores"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 4 — Evaluate dataset file"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • Click en 📋 Evaluate dataset file…"
echo " • Se abre QuickPick con todos los .json/.jsonl del workspace"
echo " • Seleccioná smoke-test.json"
echo " • Elegí agente → métricas → thresholds"
echo " • Evaluación corre → se abre RESULTS PANEL"
echo " • Mostrar el panel:"
echo "   - Score general (ej: 40% ❌)"
echo "   - N queries · X passed · Y failed"
echo "   - Filas con ✅/❌ + query + scores"
echo " • Click en una fila → se expande:"
echo "   🤖 Agent Response"
echo "   📊 Cada métrica con score y razón detallada"
echo " • Click Expand All → todas las filas expandidas"
echo " • Tick Save results as file → nombre default → 💾 Save"
echo " • Mostrar que se guardó en results/"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 5 — Custom Evaluators"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • Scroll a 🔧 Custom Evaluators en la sidebar"
echo " • Click + Add Custom Evaluator"
echo " • Name: politeness → Enter"
echo " • Se abre PANEL con textarea multilínea"
echo " • Escribir prompt: 'Is the response polite and professional? Answer YES/NO.'"
echo " • Tick ☑ Save prompt as file → nombre: politeness-custom_eval.md"
echo " • Click ✓ Save Evaluator"
echo " • Threshold: 0.8 → Enter"
echo " • Mostrar que aparece listado en la sidebar con ✕ para borrar"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 6 — API Key + Custom Eval en acción"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • 🔑 Settings → Set API Key → pegar key"
echo " • Volver a evaluar smoke-test-rag.json"
echo " • En el metrics picker ahora aparece 🔧 politeness"
echo " • Seleccionarlo junto con faithfulness y g_eval"
echo " • Mostrar que usa las 3 métricas + custom"
echo " • Resultados con métricas + razones detalladas"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 7 — CI/CD Snippet"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • Ctrl+Shift+P → AI Evaluator: Generate CI/CD Snippet"
echo " • Ingresá path: ./evals/regression.json"
echo " • Se abre pestaña con workflow YAML de GitHub Actions"
echo " • Mostrar: agent, dataset, métricas, min-score"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ESCENA 8 — Docs y Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " • 📖 Docs → Tutorials (abre aievaluator.dev/tutorials)"
echo " • 📊 Open Dashboard (abre aievaluator.dev)"
echo ""

echo "============================================"
echo " TIPS DE GRABACIÓN:"
echo "============================================"
echo " • Usá OBS o Ctrl+Shift+Alt+R en VSCode"
echo " • Mostrá los atajos de teclado en pantalla"
echo " • Si falla una eval por rate-limit, usá otra cuenta o esperá"
echo " • Mantené cada escena en 2-3 minutos"
echo " • Grabá la ventana [Extension Development Host]"
echo " • Tené las carpetas evals/ y results/ limpias antes de empezar"
echo "============================================"
